language: node_js
node_js:
  - 8.11.3
script:
  - npm test
  - npm run build
  - npm run build-demo
before_deploy:
  - touch .npmignore
deploy:
  - provider: script
    skip-cleanup: true
    script: bash deploy.sh
    on:
      branch: master
      tags: true
  - provider: pages
    local-dir: ./demo/dist
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
      tags: true
